"""BigQuery: analytics warehouse for historical telemetry, incidents and
model features. Powers Looker Studio dashboards. Demo mode serves from the
synthetic CSVs generated by data/generators."""
from pathlib import Path

import pandas as pd

from app.core.config import settings
from app.core.logging import get_logger

log = get_logger(__name__)

# repo layout first (data/samples, regenerable); bundled copy second
# (backend/demo_data, shipped in serverless deployments where ../data
# is outside the service root)
_REPO_DATA = Path(__file__).resolve().parents[3] / "data" / "samples"
_BUNDLED_DATA = Path(__file__).resolve().parents[2] / "demo_data"
DEMO_DATA_DIR = _REPO_DATA if _REPO_DATA.exists() else _BUNDLED_DATA


class BigQueryService:
    def __init__(self):
        self._client = None

    def _bq(self):
        if self._client is None:
            from google.cloud import bigquery

            self._client = bigquery.Client(project=settings.GCP_PROJECT_ID)
        return self._client

    def query(self, sql: str) -> pd.DataFrame:
        if settings.DEMO_MODE:
            raise RuntimeError("Use table() accessors in demo mode; SQL requires BigQuery.")
        return self._bq().query(sql).to_dataframe()

    def table(self, name: str) -> pd.DataFrame:
        """Load a table — BigQuery in prod, live feed or synthetic CSV in demo."""
        if settings.DEMO_MODE:
            if name == "weather_current" and settings.LIVE_WEATHER:
                from app.services.live_weather import fetch_live_weather

                live = fetch_live_weather()
                if live is not None:
                    return live
            path = DEMO_DATA_DIR / f"{name}.csv"
            if not path.exists():
                log.warning("demo_table_missing", table=name)
                return pd.DataFrame()
            return pd.read_csv(path)
        return self.query(f"SELECT * FROM `{settings.GCP_PROJECT_ID}.{settings.BQ_DATASET}.{name}`")

    def insert_rows(self, table: str, rows: list[dict]) -> None:
        if settings.DEMO_MODE:
            try:
                path = DEMO_DATA_DIR / f"{table}.csv"
                pd.DataFrame(rows).to_csv(path, mode="a", header=not path.exists(), index=False)
            except OSError:  # read-only filesystem (serverless) — skip append
                log.warning("demo_insert_skipped_readonly", table=table)
            return
        errors = self._bq().insert_rows_json(
            f"{settings.GCP_PROJECT_ID}.{settings.BQ_DATASET}.{table}", rows
        )
        if errors:
            log.error("bq_insert_errors", table=table, errors=errors)


bq = BigQueryService()
